name: ReveilDesChasseurs
version: '${project.version}'
main: fr.akashisei.reveildeschasseurs.ReveilDesChasseurs
api-version: '1.19'
depend: [MythicMobs]
authors: [Akashisei]
description: Un plugin de donjons et quêtes avec des mobs personnalisés

commands:
  dungeon:
    description: Commande principale pour les donjons
    usage: /dungeon <join|leave|list>
  quest:
    description: Commande pour gérer vos quêtes
    usage: /quest <list|start|abandon> [id]
  class:
    description: Commande pour gérer votre classe
    usage: /class <info|change> [classe]
    permission: reveildeschasseurs.command.class
  rank:
    description: Commande pour gérer votre rang
    usage: /rank [novice|apprenti|expert|maître|grand maître]
    permission: reveildeschasseurs.rank

permissions:
  reveildeschasseurs.*:
    description: Donne accès à toutes les commandes du plugin
    children:
      reveildeschasseurs.command.class: true
      reveildeschasseurs.command.dungeon: true
      reveildeschasseurs.command.quest: true
      reveildeschasseurs.command.rank: true
  reveildeschasseurs.command.class:
    description: Permet d'utiliser la commande /class
    default: true
  reveildeschasseurs.command.dungeon:
    description: Permet d'utiliser la commande /dungeon
    default: true
  reveildeschasseurs.command.quest:
    description: Permet d'utiliser la commande /quest
    default: true
  reveildeschasseurs.command.rank:
    description: Permet d'utiliser la commande /rank
    default: op 