name: ReveilDesChasseurs
version: 1.0
main: fr.akashisei.reveildeschasseurs.ReveilDesChasseurs
api-version: 1.19
depend:
  - MythicMobs
  - ItemsAdder
  - DeluxeMenus
  - Multiverse-Core
softdepend:
  - ExecutableItems
  - CustomGUI
  - UltraCustomizer
authors: [Akashisei]
description: Un plugin de donjons et quêtes avec des mobs personnalisés

commands:
  dungeon:
    description: Commande principale pour gérer les donjons
    usage: /dungeon <sous-commande>
  quest:
    description: Commande pour gérer les quêtes
    usage: /quest <sous-commande>
  profile:
    description: Commande pour gérer votre profil
    usage: /profile [view|edit]
    permission: reveildeschasseurs.command.profile
  class:
    description: Commande pour gérer les classes
    usage: /class <sous-commande>
  rank:
    description: Commande pour gérer votre rang
    usage: /rank [novice|apprenti|expert|maître|grand maître]
    permission: reveildeschasseurs.command.rank
  money:
    description: Permet de gérer votre argent
    usage: /<command> [subcommand]
    aliases: [argent]

permissions:
  reveildeschasseurs.*:
    description: Donne accès à toutes les commandes du plugin
    children:
      reveildeschasseurs.command.class: true
      reveildeschasseurs.command.dungeon: true
      reveildeschasseurs.command.quest: true
      reveildeschasseurs.command.rank: true
      reveildeschasseurs.command.profile: true
  reveildeschasseurs.command.class:
    description: Permet d'utiliser la commande /class
    default: true
  reveildeschasseurs.command.dungeon:
    description: Permet d'utiliser la commande /dungeon
    default: true
  reveildeschasseurs.command.quest:
    description: Permet d'utiliser la commande /quest
    default: true
  reveildeschasseurs.command.rank:
    description: Permet d'utiliser la commande /rank
    default: op
  reveildeschasseurs.command.profile:
    description: Permet d'utiliser la commande /profile
    default: true 